log-level: debug
disable-color: True
config: "hello"
packages:
    DEFAULT:
        test1: test1_default
        test2: test2_default
    github.com/LandonTClipp/makemocks:
        test1: test1_landon